/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.customizable.entities.example.infrastructure.controller;

import com.diegotobalina.framework.core.crud.BaseController;
import com.diegotobalina.framework.core.crud.IBaseMapper;
import com.diegotobalina.framework.core.crud.IBaseRepository;
import com.diegotobalina.framework.core.crud.services.IBaseService;
import com.diegotobalina.framework.core.crud.usecases.ICreateUseCase;
import com.diegotobalina.framework.core.crud.usecases.IDeleteUseCase;
import com.diegotobalina.framework.core.crud.usecases.IFindUseCase;
import com.diegotobalina.framework.core.crud.usecases.IUpdateUseCase;
import com.diegotobalina.framework.customizable.entities.example.application.ExampleServiceImpl;
import com.diegotobalina.framework.customizable.entities.example.application.usecase.ICreateExampleUseCase;
import com.diegotobalina.framework.customizable.entities.example.application.usecase.IDeleteExampleUseCase;
import com.diegotobalina.framework.customizable.entities.example.application.usecase.IFindExampleUseCase;
import com.diegotobalina.framework.customizable.entities.example.application.usecase.IUpdateExampleUseCase;
import com.diegotobalina.framework.customizable.entities.example.domain.Example;
import com.diegotobalina.framework.customizable.entities.example.domain.ExampleMapper;
import com.diegotobalina.framework.customizable.entities.example.domain.ExampleSpecification;
import com.diegotobalina.framework.customizable.entities.example.infrastructure.controller.dto.input.ExampleInputDTO;
import com.diegotobalina.framework.customizable.entities.example.infrastructure.controller.dto.output.BaseExampleOutputDTO;
import com.diegotobalina.framework.customizable.entities.example.infrastructure.controller.dto.output.ExampleOutputDTO;
import com.diegotobalina.framework.customizable.entities.example.infrastructure.repository.ExampleRepository;
import io.swagger.annotations.Api;
import lombok.AllArgsConstructor;
import org.mapstruct.factory.Mappers;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@Validated
@RestController
@AllArgsConstructor
@Api(tags = "Example")
@RequestMapping("/api/v0/examples")
public class ExampleController
    extends BaseController<Example, ExampleInputDTO, BaseExampleOutputDTO, ExampleOutputDTO> {

  private final IFindExampleUseCase findExampleUseCase;
  private final ICreateExampleUseCase createUseCase;
  private final IUpdateExampleUseCase updateUseCase;
  private final IDeleteExampleUseCase deleteUseCase;
  private final ExampleRepository exampleRepository;
  private final ExampleServiceImpl exampleServiceImpl;

  @Override
  protected Class<?> getSpecificationClass() {
    return ExampleSpecification.class;
  }

  @Override
  protected IBaseMapper getMapper() {
    return Mappers.getMapper(ExampleMapper.class);
  }

  @Override
  protected IFindUseCase getFindUseCase() {
    return findExampleUseCase;
  }

  @Override
  protected ICreateUseCase getCreateUseCase() {
    return createUseCase;
  }

  @Override
  protected IUpdateUseCase getUpdateUseCase() {
    return updateUseCase;
  }

  @Override
  protected IDeleteUseCase getDeleteUseCase() {
    return deleteUseCase;
  }

  @Override
  protected IBaseService getService() {
    return exampleServiceImpl;
  }

  @Override
  protected IBaseRepository getRepository() {
    return this.exampleRepository;
  }
}
