/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.customizable.entities.example.infrastructure.controller.dto.output;

import com.diegotobalina.framework.provided.ResourcePathBuilder;
import com.diegotobalina.framework.provided.responses.EntityMetadata;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@Getter
@Setter
@ToString()
public class BaseExampleOutputDTO implements Serializable, EntityMetadata {

  protected long id;

  /* FIELDS */
  @Override
  public String getPath() {
    return ResourcePathBuilder.build(String.format("/examples/%s", this.getId()));
  }
}
