/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.customizable.entities.example.application;

import com.diegotobalina.framework.customizable.entities.example.domain.Example;
import com.diegotobalina.framework.provided.interfaces.service.CachedCrudServiceService;
import org.springframework.stereotype.Service;

@Service
public class CachedExampleService implements CachedCrudServiceService<Example> {}
