/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.customizable.entities.example.application;

import com.diegotobalina.framework.core.crud.services.IBaseService;
import com.diegotobalina.framework.customizable.entities.example.domain.Example;
import org.springframework.stereotype.Service;

@Service
public class ExampleServiceImpl implements IBaseService<Example> {}
