/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.core.crud.usecases;

import com.diegotobalina.framework.core.crud.BaseEntity;
import com.diegotobalina.framework.core.crud.services.IBaseService;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ICreateUseCase<T extends BaseEntity> {
  default T create(T t, IBaseService<T> service, JpaRepository<T, Long> repository) {
    preSave(t, service, repository);
    T save = service.save(t, repository);
    postSave(t, service, repository);
    return save;
  }

  void preSave(T t, IBaseService<T> service, JpaRepository<T, Long> repository);

  void postSave(T t, IBaseService<T> service, JpaRepository<T, Long> repository);
}
