/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.core.crud.usecases;

import com.diegotobalina.framework.core.crud.StaffitEntity;
import com.diegotobalina.framework.core.crud.services.ICrudService;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ICreateUseCase<T extends StaffitEntity> {
    default T create(T t, ICrudService<T> service, JpaRepository<T, Long> repository) {
        preSave(t, service, repository);
        T save = service.save(t, repository);
        postSave(t, service, repository);
        return save;
    }

    void preSave(T t, ICrudService<T> service, JpaRepository<T, Long> repository);

    void postSave(T t, ICrudService<T> service, JpaRepository<T, Long> repository);
}
