/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.provided.interfaces.usecase;

import com.diegotobalina.framework.provided.interfaces.service.CrudService;
import com.diegotobalina.framework.provided.interfaces.entity.CustomEntity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface DeleteUseCase<T extends CustomEntity> {
  default T delete(long id, CrudService<T> service, JpaRepository<T, Long> repository) {
    preLoad(id, service, repository);
    T t = service.findById(id, repository);
    postLoad(t, service, repository);
    service.deleteById(id, repository);
    postDelete(t, service, repository);
    return t;
  }

  void preLoad(long id, CrudService<T> service, JpaRepository<T, Long> repository);

  void postLoad(T t, CrudService<T> service, JpaRepository<T, Long> repository);

  void postDelete(T t, CrudService<T> service, JpaRepository<T, Long> repository);
}
