/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.provided.multitenant.tenantdatasource.infrastructure.repository;

import com.diegotobalina.framework.provided.multitenant.tenantdatasource.domain.TenantDataSource;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

@Repository
public interface TenantDataSourceRepository
    extends JpaRepository<TenantDataSource, Long>, JpaSpecificationExecutor<TenantDataSource> {
  TenantDataSource findByHeaderTokenAndActive(String headerToken, boolean active);
}
