/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.provided.multitenant.tenantdatasource.infrastructure.controller.dto.input;

import lombok.AllArgsConstructor;
import lombok.SneakyThrows;
import org.springframework.stereotype.Component;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

@Component
@AllArgsConstructor
public class TenantDataSourceInputDTOValidator
    implements ConstraintValidator<TenantDataSourceInputDTOConstraint, TenantDataSourceInputDTO> {

  @Override
  public void initialize(TenantDataSourceInputDTOConstraint constraintAnnotation) {
    // empty
  }

  @SneakyThrows
  @Override
  public boolean isValid(
      TenantDataSourceInputDTO tenantdatasourceInputDTO,
      ConstraintValidatorContext constraintValidatorContext) {
    return true;
  }
}
