/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.provided.multitenant.tenantdatasource.infrastructure.controller.dto.input;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import java.io.Serializable;

@Getter
@Setter
@ToString(callSuper = true)
@TenantDataSourceInputDTOConstraint
public class TenantDataSourceInputDTO implements Serializable {

  @NotEmpty
  @ApiModelProperty(example = "Postgres1")
  protected String name;

  @NotEmpty
  @ApiModelProperty(example = "Base de datos por defecto")
  protected String description;

  @NotEmpty
  @ApiModelProperty(example = "Postgres1")
  protected String headerToken;

  @NotEmpty
  @ApiModelProperty(
      example = "jdbc:postgresql://localhost:5432/postgres?ApplicationName=MultiTenant")
  protected String url;

  @NotEmpty
  @ApiModelProperty(example = "postgres")
  protected String username;

  @NotEmpty
  @ApiModelProperty(example = "password")
  protected String password;

  @NotEmpty
  @ApiModelProperty(example = "org.postgresql.Driver")
  protected String driverClassName;

  @NotNull
  @ApiModelProperty(example = "true")
  protected boolean active;
}
