/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.provided.multitenant.tenantdatasource.infrastructure.controller.dto.output;

import com.diegotobalina.framework.provided.ResourcePathBuilder;
import com.diegotobalina.framework.provided.responses.EntityMetadata;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@Getter
@Setter
@ToString()
public class BaseTenantDataSourceOutputDTO implements Serializable, EntityMetadata {

  protected long id;
  protected String name;
  protected String description;
  protected String headerToken;
  protected String url;
  protected String username;
  protected String password;
  protected String driverClassName;
  protected boolean active;

  @Override
  public String getPath() {
    return ResourcePathBuilder.build(String.format("/tenantdatasources/%s", this.getId()));
  }
}
