/* Autogenerated file. Do not edit manually. */

package com.xbidi.spring.content.example.application.usecase;

import com.xbidi.spring.content.example.domain.Example;

public interface FindExampleUseCase {
  Example findById(long id);

  Example findByIdOrNull(long id);
}
