/* Autogenerated file. Do not edit manually. */

package com.xbidi.spring.content.example.application.usecase;

import com.xbidi.spring.content.example.application.ExampleService;
import com.xbidi.spring.content.example.domain.Example;
import com.xbidi.spring.content.shared.anotation.UseCase;

@UseCase
public class FindExampleUseCaseImpl implements FindExampleUseCase {

  private final ExampleService exampleService;

  public FindExampleUseCaseImpl(ExampleService exampleService) {
    this.exampleService = exampleService;
  }

  @Override
  public Example findById(long id) {
    return this.exampleService.findById(id);
  }

  @Override
  public Example findByIdOrNull(long id) {
    return this.exampleService.findByIdOrNull(id);
  }
}
