/* Autogenerated file. Do not edit manually. */

package com.xbidi.spring.content.example.application.usecase;

import com.xbidi.spring.content.example.domain.Example;
import com.xbidi.spring.exception.exception.EntityNotFoundException;

public interface UpdateExampleUseCase {
  Example update(long id, Object object) throws EntityNotFoundException;
}
