/* Autogenerated file. Do not edit manually. */

package com.xbidi.spring.content.example.application.usecase;

import com.xbidi.spring.content.example.application.ExampleService;
import com.xbidi.spring.content.example.domain.Example;
import com.xbidi.spring.content.shared.anotation.UseCase;
import lombok.AllArgsConstructor;

@UseCase
@AllArgsConstructor
public class UpdateExampleUseCaseImpl implements UpdateExampleUseCase {

  private FindExampleUseCase findExampleUseCase;
  private ExampleService exampleService;

  @Override
  public Example update(long id, Object object) {
    Example actualExample = findExampleUseCase.findById(id);
    actualExample.update(object, new String[] {"id"});
    return exampleService.save(actualExample);
  }
}
