/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.provided.interfaces.entity;

import com.diegotobalina.framework.provided.exception.exception.EntityNotValidException;
import org.springframework.stereotype.Component;

import javax.persistence.*;

@Component
public class CustomEntityListener {

  @PrePersist
  public void prePersist(Object o) throws EntityNotValidException {
    if (o instanceof CustomEntity customEntity) {
      customEntity.checkIfCanBeInserted(customEntity);
    }
  }

  @PreUpdate
  public void preUpdate(Object o) throws EntityNotValidException {
    if (o instanceof CustomEntity customEntity) {
      customEntity.checkIfCanBeInserted(customEntity);
    }
  }

  @PreRemove
  public void preRemove(Object o) {/* empty */}

  @PostLoad
  public void postLoad(Object o) {/* empty */}

  @PostPersist
  public void postPersist(Object o) {/* empty */}

  @PostUpdate
  public void postUpdate(Object o) {/* empty */}

  @PostRemove
  public void postRemove(Object o) {/* empty */}
}
