/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.provided.interfaces.entity;

import com.diegotobalina.framework.provided.auditable.Auditable;

public abstract class CustomEntity extends Auditable<String> implements Valid, Updatable {}
