/* Autogenerated file. Do not edit manually. */

package com.xbidi.spring.content.example.infrastructure.controller.dto.output;

import com.xbidi.spring.content.shared.ResourcePathBuilder;
import com.xbidi.spring.content.shared.interfaces.dto.output.APIMetadata;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@Getter
@Setter
@ToString()
public class BaseExampleOutputDTO implements Serializable, APIMetadata {

  protected long id;

  /* FIELDS */
  @Override
  public String getPath() {
    return ResourcePathBuilder.build(String.format("/examples/%s", this.getId()));
  }
}
