/* Autogenerated file. Do not edit manually. */

package com.xbidi.spring.content.example.application;

import com.xbidi.spring.content.example.domain.Example;
import com.xbidi.spring.content.shared.interfaces.service.Crud;

public interface CachedExampleService extends Crud<Example> {}
