/* Autogenerated file. Do not edit manually. */

package com.xbidi.spring.content.example.application;

import com.xbidi.spring.content.example.domain.Example;
import com.xbidi.spring.content.example.infrastructure.repository.ExampleRepository;
import com.xbidi.spring.content.shared.Constants;
import lombok.Getter;
import lombok.Setter;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.stereotype.Service;

import javax.persistence.EntityNotFoundException;
import java.util.List;

@Service
public class ExampleServiceImpl implements ExampleService, InitializingBean {

  // ----------- Repository -----------

  @Getter @Setter private static ExampleService instance;
  private final ExampleRepository exampleRepository;

  // ----------- Instance -----------

  public ExampleServiceImpl(ExampleRepository exampleRepository) {
    this.exampleRepository = exampleRepository;
  }

  @Override
  public void afterPropertiesSet() {
    setInstance(this);
  }

  // ----------- Public methods -----------

  @Override
  public Example findById(long id) {
    var className = Example.class.getSimpleName();
    var errorMessage = String.format(Constants.ERROR_ENTITY_NOT_FOUND_WITH_ID, className, id);
    return this.exampleRepository
        .findById(id)
        .orElseThrow(() -> new EntityNotFoundException(errorMessage));
  }

  @Override
  public Example findByIdOrNull(long id) {
    return this.exampleRepository.findById(id).orElse(null);
  }

  @Override
  public List<Example> findAllByIds(List<Long> ids) {
    if (ids == null) {
      var errorMessage = String.format(Constants.ERROR_PARAMETER_CANT_BE_NULL, "ids");
      throw new IllegalArgumentException(errorMessage);
    }
    return this.exampleRepository.findAllById(ids);
  }

  @Override
  public Example save(Example example) {
    if (example == null) {
      var errorMessage = String.format(Constants.ERROR_PARAMETER_CANT_BE_NULL, "example");
      throw new IllegalArgumentException(errorMessage);
    }
    return this.exampleRepository.save(example);
  }

  @Override
  public List<Example> saveAll(List<Example> examples) {
    if (examples == null) {
      var errorMessage = String.format(Constants.ERROR_PARAMETER_CANT_BE_NULL, "examples");
      throw new IllegalArgumentException(errorMessage);
    }
    return this.exampleRepository.saveAll(examples);
  }

  @Override
  public void deleteById(long id) {
    this.exampleRepository.deleteById(id);
  }

  @Override
  public void deleteAllById(List<Long> ids) {
    if (ids == null) {
      var errorMessage = String.format(Constants.ERROR_PARAMETER_CANT_BE_NULL, "ids");
      throw new IllegalArgumentException(errorMessage);
    }
    this.exampleRepository.deleteAllById(ids);
  }

  // ----------- Private methods -----------
}
