/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.customizable.entities.example.domain;

import com.diegotobalina.framework.provided.interfaces.entity.CustomEntity;
import com.diegotobalina.framework.provided.interfaces.entity.CustomEntityListener;
import lombok.*;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;
import org.hibernate.envers.Audited;

import javax.persistence.*;

@Setter
@Getter
@Entity
@Audited
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "O_MSTR_EXAMPLE")
@FilterDef(
    name = "tenantFilter",
    parameters = {@ParamDef(name = "tenantId", type = "string")})
@Filter(name = "tenantFilter", condition = "tenant_id = :tenantId")
@EntityListeners({CustomEntityListener.class, ExampleListener.class})
public class Example extends CustomEntity {

  @Id
  @GeneratedValue
  @Column(name = "ID")
  protected Long id;

  /* FIELDS */

  @Override
  public String getNotValidCause() {
    return null;
  }
}
