/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.customizable.entities.example.domain;

import org.springframework.stereotype.Component;

import javax.persistence.*;

@Component
public class ExampleListener {

    @PrePersist
    public void prePersist(Example example) {/* implement */}

    @PreUpdate
    public void preUpdate(Example example) {/* implement */}

    @PreRemove
    public void preRemove(Example example) {/* implement */}

    @PostLoad
    public void postLoad(Example example) {/* implement */}

    @PostPersist
    public void postPersist(Example example) {/* implement */}

    @PostUpdate
    public void postUpdate(Example example) {/* implement */}

    @PostRemove
    public void postRemove(Example example) {/* implement */}
}
