/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.customizable.entities.example.domain;

import com.diegotobalina.framework.core.crud.StaffitEntity;
import lombok.*;

import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;

@Getter
@Setter
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "o_mstr_example")
@EntityListeners(ExampleListener.class)
public class Example extends StaffitEntity {

    protected String name;
    protected String description;
    protected String email;

    @Override
    public String getNotValidCause() {
        return null;
    }
}
