/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.customizable.entities.example.domain;

import org.springframework.stereotype.Component;

import javax.persistence.*;

@Component
public class ExampleListener {

  @PrePersist
  public void prePersist(Example example) {/* empty */}

  @PreUpdate
  public void preUpdate(Example example) {/* empty */}

  @PreRemove
  public void preRemove(Example example) {/* empty */}

  @PostLoad
  public void postLoad(Example example) {/* empty */}

  @PostPersist
  public void postPersist(Example example) {/* empty */}

  @PostUpdate
  public void postUpdate(Example example) {/* empty */}

  @PostRemove
  public void postRemove(Example example) {/* empty */}
}
