/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.core.crud;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@Getter
@Setter
@ToString(callSuper = true)
public abstract class StaffitInputDTO implements Serializable {
}
