/* Autogenerated file. Do not edit manually. */

package com.xbidi.spring.content.example.infrastructure.controller.dto.input;

import com.xbidi.spring.content.shared.Constants;

import javax.validation.Constraint;
import javax.validation.Payload;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Constraint(validatedBy = ExampleInputDTOValidator.class)
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface ExampleInputDTOConstraint {
  String message() default Constants.ERROR_INPUT_DTO_FORMAT_NOT_VALID;

  Class<?>[] groups() default {};

  Class<? extends Payload>[] payload() default {};
}
