/* Autogenerated file. Do not edit manually. */

package com.xbidi.spring.content.example.infrastructure.controller.dto.input;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@Getter
@Setter
@ToString(callSuper = true)
@ExampleInputDTOConstraint
public class ExampleInputDTO implements Serializable {
  /* FIELDS */
}
