/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.provided.multitenant.tenantdatasource.domain;

import org.springframework.stereotype.Component;

import javax.persistence.*;

@Component
public class TenantDataSourceListener {

  @PrePersist
  public void prePersist(TenantDataSource tenantdatasource) {/* empty */}

  @PreUpdate
  public void preUpdate(TenantDataSource tenantdatasource) {/* empty */}

  @PreRemove
  public void preRemove(TenantDataSource tenantdatasource) {/* empty */}

  @PostLoad
  public void postLoad(TenantDataSource tenantdatasource) {/* empty */}

  @PostPersist
  public void postPersist(TenantDataSource tenantdatasource) {/* empty */}

  @PostUpdate
  public void postUpdate(TenantDataSource tenantdatasource) {/* empty */}

  @PostRemove
  public void postRemove(TenantDataSource tenantdatasource) {/* empty */}
}
