/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.provided.multitenant.tenantdatasource.application;

import com.diegotobalina.framework.provided.multitenant.tenantdatasource.domain.TenantDataSource;
import com.diegotobalina.framework.provided.interfaces.service.CachedCrudServiceService;
import org.springframework.stereotype.Service;

@Service
public class CachedTenantDataSourceService implements CachedCrudServiceService<TenantDataSource> {}
