/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.provided.multitenant.tenantdatasource.application;

import com.diegotobalina.framework.provided.multitenant.tenantdatasource.domain.TenantDataSource;
import com.diegotobalina.framework.provided.interfaces.service.CrudService;
import org.springframework.stereotype.Service;

@Service
public class TenantDataSourceService implements CrudService<TenantDataSource> {}
