/* Autogenerated file. Do not edit manually. */

package com.xbidi.spring.content.example.domain;

import com.xbidi.spring.exception.exception.EntityNotValidException;
import org.springframework.stereotype.Component;

import javax.persistence.*;

@Component
public class ExampleListener {

  @PrePersist
  public void prePersist(Example example) throws EntityNotValidException {
    example.checkIfCanBeInserted(example);
  }

  @PreUpdate
  public void preUpdate(Example example) throws EntityNotValidException {
    example.checkIfCanBeInserted(example);
  }

  @PreRemove
  public void preRemove(Example example) {
    // empty
  }

  @PostLoad
  public void postLoad(Example example) { // empty
  }

  @PostPersist
  public void postPersist(Example example) { // empty
  }

  @PostUpdate
  public void postUpdate(Example example) { // empty
  }

  @PostRemove
  public void postRemove(Example example) { // empty
  }
}
