/* Autogenerated file. Do not edit manually. */

package com.xbidi.spring.content.example.infrastructure.repository;

import com.xbidi.spring.content.example.domain.Example;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

@Repository
public interface ExampleRepository
    extends JpaRepository<Example, Long>, JpaSpecificationExecutor<Example> {}
