/* Autogenerated file. Do not edit manually. */

package com.diegotobalina.framework.customizable.entities.example.infrastructure.controller.dto.input;

import com.diegotobalina.framework.core.crud.BaseInputDTO;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@Getter
@Setter
@ToString(callSuper = true)
@ExampleInputDTOConstraint
public class ExampleInputDTO extends BaseInputDTO implements Serializable {

  protected String name;
  protected String description;
  protected String email;
}
